

get http://localhost:3004/person/

###


POST http://localhost:3004/person/
Content-Type: application/json

{"name":"naveenkumar",
"age":"34",
"gender":"female",
"mobileNumber":"8008638625",
"GovtID":"PAN",
"aadhaarNumber":"dfgh",
"guardianType":"D/O",
"gurdian":"munemma",
"email":"ynavingmailcom",
"emergencyNumber":"4545454545",
"address":"f2_83_block",
"state":"Jharkhand",
"city":"Ramgarh",
"country":"India",
"pincode":"517520",
"occupation":"nothing",
"religion":"Judaism",
"maritalStatus":"unmarried",
"bloodGroup":"O+",
"nationality":"India",
"panNumber":"abcde1234f"
}